name: py310
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.10.19
  - readline=8.3
  - sqlite=3.51.0
  - tk=8.6.15
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - aiocoap==0.4.17
      - albucore==0.0.14
      - albumentations==1.4.14
      - aliyun-python-sdk-core==2.15.2
      - aliyun-python-sdk-kms==2.16.5
      - annotated-types==0.7.0
      - anyio==3.7.1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - argparse==1.4.0
      - asttokens==2.4.1
      - attrs==24.2.0
      - batchgenerators==0.25
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cachetools==4.2.4
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.3.0
      - crcmod==1.7
      - cryptography==43.0.1
      - cycler==0.12.1
      - cython==3.0.11
      - debugpy==1.8.5
      - decorator==5.1.1
      - defusedxml==0.7.1
      - einops==0.8.1
      - entrypoints==0.4
      - eval-type-backport==0.2.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastjsonschema==2.20.0
      - filelock==3.14.0
      - fonttools==4.53.1
      - fsspec==2024.9.0
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - google-auth==1.35.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.66.1
      - huggingface-hub==0.24.6
      - idna==3.8
      - imageio==2.35.1
      - importlib-metadata==8.4.0
      - importlib-resources==6.4.4
      - iopath==0.1.10
      - ipykernel==6.17.1
      - ipython==8.18.1
      - ipython-genutils==0.2.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - jmespath==0.10.0
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==7.3.4
      - jupyter-core==4.12.0
      - jupyter-server==1.24.0
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - linecache2==1.0.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.0.2
      - mmcv==2.0.0rc4
      - mmdet==3.3.0
      - mmengine==0.10.4
      - mmsegmentation==1.2.0
      - model-index==0.1.11
      - mpmath==1.3.0
      - nbclassic==1.1.0
      - nbclient==0.6.3
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest==0.4.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - nibabel==5.3.2
      - ninja==1.11.1.1
      - notebook==6.5.7
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.68
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.1
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.1
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.2.2
      - portalocker==3.1.1
      - prettytable==3.11.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - protobuf==5.28.0
      - psutil==6.0.0
      - ptflops==0.7.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycocotools==2.0.8
      - pycparser==2.22
      - pycryptodome==3.20.0
      - pydantic==2.9.0
      - pydantic-core==2.23.2
      - pygments==2.18.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pywavelets==1.6.0
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - requests==2.28.2
      - requests-oauthlib==2.0.0
      - rich==13.4.2
      - rpds-py==0.20.0
      - rsa==4.9
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - safetensors==0.4.3
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - send2trash==1.8.0
      - setuptools==60.2.0
      - shapely==2.0.7
      - six==1.16.0
      - sniffio==1.2.0
      - soupsieve==2.6
      - stack-data==0.6.3
      - supervisor==4.2.2
      - sympy==1.13.2
      - tabulate==0.9.0
      - tensorboard==2.6.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.0
      - termcolor==2.4.0
      - terminado==0.12.1
      - terminaltables==3.1.10
      - testpath==0.5.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==0.9.16
      - tinycss2==1.3.0
      - tomli==2.0.1
      - torch==2.4.1
      - torchvision==0.19.1
      - tornado==6.1
      - tqdm==4.65.2
      - traceback2==1.4.0
      - traitlets==5.1.0
      - triton==3.0.0
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - unittest2==1.1.0
      - urllib3==1.26.20
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - websocket-client==1.2.1
      - werkzeug==2.0.1
      - wheel==0.43.0
      - widgetsnbextension==3.5.1
      - yacs==0.1.8
      - yapf==0.40.2
      - zipp==3.18.1
